language: erlang
script: "make test"
notifications:
  recipients:
    - andrei.neculau@klarna.com
otp_release:
  - R16B
  - R15B03-1
  - R15B03
  - R15B02
  - R15B01
  - R15B
  - R14B04
  - R14B03
  - R14B02
