language:
  - erlang
otp_release:
  - 17.3
  - 17.1
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R15B03
  - R15B02
  - R15B01
  - R15B
script:
  - "[[ ${TRAVIS_OTP_RELEASE} == 17.3 ]] && make elvis || true"
  - make
  - make test
