sudo: false
language:
  - erlang
otp_release:
  - 22.0
  - 21.3
  - 21.2
  - 21.1
  - 21.0
  - 20.1
  - 20.0
  - 19.3
  - 19.2
  - 19.1
  - 19.0
  - 18.3
  - 18.2
  - 18.1
  - 18.0
script:
  - LATEST_OTP_RELEASE=22.0
  - "[[ ${TRAVIS_OTP_RELEASE} != ${LATEST_OTP_RELEASE} ]] || make elvis"
  - make
  - make .rebar/DEV_MODE deps xref eunit
  - "[[ ${TRAVIS_OTP_RELEASE} != ${LATEST_OTP_RELEASE} ]] || make test_cli"
  - "[[ ${TRAVIS_OTP_RELEASE} != ${LATEST_OTP_RELEASE} ]] || make dialyzer"
  - make clean .rebar/BARE_MODE # TEST BARE_MODE AS WELL
  - make
  - make .rebar/DEV_MODE deps xref
  - "[[ ${TRAVIS_OTP_RELEASE} != ${LATEST_OTP_RELEASE} ]] || make test_cli"
  - "[[ ${TRAVIS_OTP_RELEASE} != ${LATEST_OTP_RELEASE} ]] || make dialyzer"
